name: daily_globe_api
description: A Daily Globe server app built with the dart_frog package.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  collection: ^1.18.0
  dart_frog: ^1.0.0
  equatable: ^2.0.5
  http: ^1.1.0
  json_annotation: ^4.8.1
  news_blocks:
    path: packages/news_blocks

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  test: ^1.24.5
  very_good_analysis: ^5.0.0+1
